services:
  proxy:
    build: .
    container_name: teldrive-go-proxy
    ports:
      - "8888:8888"
    env_file:
      - .env
    # Increase the file descriptor limit to handle high-concurrency
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped